name: Docker CI Pipeline
on:
  push:
    branches: [ feature_actions ]


jobs:
  docker-ci-pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

        
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_ACTIONS_TOKEN }}
          
      - name: Docker Metadata action
        id: metadata_gen
        uses: docker/metadata-action@v5.7.0
        with:
          images: cmuriukin/new-era-class-23

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: ${{ steps.metadata_gen.outputs.tags }}

      
          
      

     
      
      
